@host=http://localhost:8080/api/v1
@apiKey=8ac9cdd16170aa39ce649a53be832ba0ac326de8773bd25204178395fac8c740
@clientId=6832d33d236c9f3d11508b3d
@browserId=rest-client
@acctionToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODMyZDMzZDIzNmM5ZjNkMTE1MDhiM2QiLCJlbWFpbCI6Imljb25pY3RhbGVudHMudGVhbUBnbWFpbC5jb20iLCJicm93c2VySWQiOiJyZXN0LWNsaWVudCIsImlhdCI6MTc1MTM1OTY4MiwiZXhwIjoxNzUxNDQ2MDgyfQ.QipXchaBcbMVcG3z7WKihx_qWBRSBZ30R7U0csWtCJoinnonrAqW-AfAcH4CwjLMPpS6kGbapJ1B-tik-lOSKzGVZ-D0QyMjOZTbIJdGpDIIq8nPMnaAqQ1xNBGrd7tNAMp2Y5bNcgKm1N1p5yuCb1_wNXRE4_197EmE06efbKhzWxsNEY59buSzznJrj6kzQ1wo0CViRK8nZjoJHQIK9DpnHk81Qcrke1jWpkce4b1N9UilQazZw0VtvGnt4Hf6PUW_wRpDjqJQ6thAhN4QwGk0VhGW4aod-IfujXI2s8goKdkXM3l82jRFC2Ogk5Zi6S6c-O_LKrlcgLVqKC29fw
@refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODMyZDMzZDIzNmM5ZjNkMTE1MDhiM2QiLCJlbWFpbCI6Imljb25pY3RhbGVudHMudGVhbUBnbWFpbC5jb20iLCJicm93c2VySWQiOiJyZXN0LWNsaWVudCIsImlhdCI6MTc1MTM1OTY4MiwiZXhwIjoxNzUxOTY0NDgyfQ.hEf1uYPN_fThdu1vic9CGSCJ49Y1jvgWfcx7eqxtucgmbA3EDec6kgpPxykoZmHR1L8inSIBL5sVwoEKrpQ7cAmfvSAhnq9VaBX5m35p4tpX9ubWq986GhkF8XOaGoxpByJTdgKbkSOhPixyI_92q0k6bQ6JufCPKOBPWK6HFVcI6zm0dXd_twzUKrxFWGvKM944jTOg646yiKHeFih-g2sHIWnRyrVPEjL65xqEapFCHQZA4Nq0l-FpHY7Pta-RRonNzSKQzQbP9uhUmBPod6bTSkC9GmYroHUSyFJ61lZbqtN7LTvSZtVdjuUoXNxYGYNFno4T0Et5vj4LOCjqog

POST {{host}}/auth/signin HTTP/1.1
Content-type: application/json
x-api-key: {{apiKey}}

{
    "username": "cube",
    "password": "hi",
    "browserId": "{{browserId}}"
}

###

POST {{host}}/resources HTTP/1.1
Content-type: application/json
x-api-key: {{apiKey}}
Authorization: Bearer {{acctionToken}}
x-client-id: {{clientId}}


{
    "name": "Reward Management",
    "slug": "reward",
    "description": "Quản lý quỹ thưởng"
}

### 6863a0ed8cdebe15963b9d2e

GET {{host}}/roles/admin HTTP/1.1
x-api-key: {{apiKey}}
Authorization: Bearer {{acctionToken}}
x-client-id: {{clientId}}

### 

POST {{host}}/roles/admin/grants HTTP/1.1
Content-type: application/json
x-api-key: {{apiKey}}
Authorization: Bearer {{acctionToken}}
x-client-id: {{clientId}}

{
    "grants": [
        {
        "resourceId": "6863a0ed8cdebe15963b9d2e",
        "actions": [
            "read:any",
            "create:any",
            "update:any",
            "delete:any"
        ]}
    ]
}